config/routes.rb
Myapp::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  post '/change_to_artist' => 'users#change_to_artist'

  get 'tattoos/most_liked' => 'tattoos#most_liked'


  authenticated :user do
    root :to => 'tattoos#index'
  end
  root :to => "home#index"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  ActiveAdmin.routes(self)
  resources :users
  match 'preview' => 'tattoos#preview'
  get 'search' => 'search#search'
  match 'about' => 'home#about'
  match 'quickpreview' => 'home#quickpreview'
  resources :tattoos do
    resources :comments
    member do 
      post :vote_up
      post :vote_down
    end
  end

 
 resources :artists do
    resources :tattoos
    resources :comments
  end
  resources :artist_steps
   post '/artists/:artist_id/comments' => 'comments#create', as: 'create_comment'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  belongs_to :user
  has_many :tattoos
  has_many :comments
  attr_accessible :last_name, :first_name, :full_name, :location, :tattoo_shop, :avatar, :specialties, :bio, :instagram, :flickr, :twitter, :facebook, :cover_tattoo, :user_id, :email, :phone, :tattoo_shop_url, :color_scheme, :vanity_url
  attr_accessible :id, :first_name, :last_name, :full_name, :location, 
                  :tattoo_shop, :avatar, :specialties, :bio, :instagram, 
                  :flickr, :twitter, :facebook, :cover_photo, :created_at, 
                  :updated_at, :user_id, :tattoo_shop_url, :email, :phone, 
                  :color_scheme, :vanity_url, :as => [:default, :admin]

  mount_uploader :avatar, AvatarUploader
  mount_uploader :cover_photo, CoverphotoUploader


  require "uri"
  validates_uniqueness_of :vanity_url, allow_blank: true, :message => 'url not available'
  validates_format_of :vanity_url, :without => /^\d/, allow_blank:true
  validates_presence_of :first_name
  validates :twitter, :format => { without: /\W/, allow_blank: true, :message => 'Enter a vaild twitter handle without @, or a link to your twitter.'}
  validates :flickr, :format => { without: /\W/, allow_blank: true, :message => 'Enter a valid flickr username or a link to your flickr profile.'}
  validates :instagram, :format => { without: /\W/, allow_blank: true, :message => 'Enter a valid instagram username without @, or a link to your instagram profile.'}
  validates :facebook, :format => { without: /\W/, allow_blank: true, :message => 'Enter a valid facebook url.'}
  # validates_presence_of :bio, :message => 'Please enter a short bio. We want to know something about you!'
  # validates_presence_of :specialties, :message => "We know you're good at something!"

  # Public: Creates a "full name" for the artist, which is a combination of first and last name
  # If only first name exists, full name is set as first name
  # Will be used for searching through artists and potentially for artist route
  def full_name
    if self.first_name && self.last_name
      full_name = "#{self.first_name} #{self.last_name}"
      self.full_name = full_name
    else
      self.full_name = self.first_name
    end
  end

  def to_param
    self.vanity_url
  end

  def self.find(input)
    if input.to_i != 0
      super
    else
        find_by_vanity_url(input)
    end
  end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
    @comment = @artist.comments.build
    @comments = @artist.comments
  end

  def new
    if current_user.artist
      redirect_to artist_path(current_user.artist)
    end

    @artist = Artist.new
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  # Creates the artist through the user model
  def create
    @artist = current_user.build_artist(params[:artist])
    if @artist.save
      redirect_to artist_steps_path
    else
      render :new
    end
  end

  def update
    @artist = Artist.find(params[:id])

    respond_to do |format|
      if @artist.update_attributes(params[:artist])
        format.html { redirect_to @artist, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  end

  def favorite
  end

  def unfavorite
  end
end

app/helpers/artist_helper.rb
module ArtistHelper

  # Public: Determine if the user has entered a social handle
  #
  # artist - The current pages' artist id
  # social_network - The :symbol of the social network
  # &block - indicates that the method will be followed by a block
  #
  # Returns true if social handle exists and prints block
  def if_social(artist, social_network, &block)
    if !artist[social_network].blank?
      content_tag(:span, capture(&block))
    end 
  end

  # Public: Takes a user's input from social fields and parses it to see whether it starts with http://
  # This method is called from within build_link.
  #
  # url - A url supplied by the user
  #
  # Returns a full link with in http:// scheme
  def add_http(url)
    u=URI.parse(url)
    if (!u.scheme)
        return link = "http://" + url
    else
        return link = url
    end
  end

  # Public: Builds a functional link from whatever input a user makes in social fields
  #
  # artist - The current pages' artist id
  # social_network - The :symbol of the social network
  def build_link(artist, social_network)
    if artist[social_network].include?('/')
      link = add_http(artist[social_network])
    else
      link = "http://www." + social_network.to_s + ".com/#{artist[social_network]}"
    end
    link_to image_tag("#{social_network}-4-48.png"), link
  end

end

  # Public: Supplies default image if avatar is not present.

  def artist_av(artist)
    if artist.avatar
      image_tag ("#{artist.avatar}")
    else
      image_tag ("avatardefault.gif")
    end
  end

app/views/artists/_reviews.html.erb
<h3>
  <%= "#{@artist.full_name}'s Reviews" %>
</h3>
<% @comments.each do |comment| %>
  <% if comment.id %>
    <div class="comment_div">
      <div class="user">
        <%= link_to comment.user.username, comment.user %>
      </div>
      <div class="comment_content">
        <%= comment.comment_content %>
      </div>
    </div>
    <% if comment.user == current_user %>
      <div class="comment_delete">
        <%= link_to 'Delete Review', artist_comment_path(@artist.id, comment), method: :delete, data: { confirm: 'Are you sure?' }  %>
      </div>
    <% end %>
  <% end %>
<% end %>
<hr/>
<%= form_for(@comment, :url => "/artists/#{@artist.id}/comments") do |f| %>
  <% if @comment.errors.any?  %>
    <div id="error_explanation">

app/views/artists/_reviews.html.haml
%h3= "#{@artist.full_name}'s Reviews"
- @comments.each do |comment|
  - if comment.id
    .comment_div
      %div.user= link_to comment.user.username, comment.user
      %div.comment_content= comment.comment_content
    - if comment.user == current_user
      %div.comment_delete= link_to 'Delete Review', artist_comment_path(@artist.id, comment), method: :delete, data: { confirm: 'Are you sure?' } 

%hr
= form_for(@comment, :url => "/artists/#{@artist.id}/comments") do |f|

  - if @comment.errors.any? 
    #error_explanation
      %h2= pluralize(@comment.errors.count, "error") +'prohibited this comment from being saved:'

  %ul
    - @artist.errors.full_messages.each do |msg| 
      %li= msg

  .field
    = f.text_area :comment_content, :placeholder => "What do you think of #{@artist.full_name}'s work?"
  
  = f.submit "Review #{@artist.full_name}", class: 'button tiny'

app/views/artists/create.html.erb
<h1>Artist#create</h1>
<p>Find me in app/views/artist/create.html.erb</p>

app/views/artists/create.html.haml
%h1 Artist#create
%p Find me in app/views/artist/create.html.haml

app/views/artists/destroy.html.erb
<h1>Artist#destroy</h1>
<p>Find me in app/views/artist/destroy.html.erb</p>

app/views/artists/destroy.html.haml
%h1 Artist#destroy
%p Find me in app/views/artist/destroy.html.haml

app/views/artists/edit.html.erb
<h2>Edit Your Artist Portfolio</h2>
<%= simple_form_for(@artist) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <%= f.input :first_name %>
  </div>
  <div class="field">
    <%= f.input :last_name %>
  </div>
  <div class="field">
    <%= f.input :location %>
  </div>
  <div class="field">
    <%= f.input :tattoo_shop %>
  </div>
  <div class="field">
    <%= f.input :tattoo_shop_url, :label => "Tattoo shop website" %>
  </div>
  <div class="field">
    <%= f.input :bio %>
  </div>
  <div class="field">
    <%= f.input :specialties %>
  </div>
  <div class="field">
    <%= f.input :instagram %>
  </div>
  <div class="field">
    <%= f.input :twitter %>
  </div>
  <div class="field">
    <%= f.input :flickr %>
  </div>
  <div class="field">
    <%= f.input :facebook %>
  </div>
  <div class="field">
    <%= f.input :email %>
  </div>
  <div class="form_actions">
    <%= f.button :submit, "Next", class: 'button' %>
  </div>
<% end %>

app/views/artists/edit.html.haml
%h2 Edit Your Artist Portfolio
= simple_form_for(@artist) do |f|
  = f.error_notification

  .field
    = f.input :first_name

  .field
    = f.input :last_name

  .field
    = f.input :location

  .field
    = f.input :tattoo_shop

  .field 
    = f.input :tattoo_shop_url, :label => "Tattoo shop website"

  .field
    = f.input :bio

  .field
    = f.input :specialties

  .field
    = f.input :twitter

  .field
    = f.input :instagram

  / .field
  /   = f.input :flickr

  .field
    = f.input :facebook

  .field
    = f.input :email

  .field
    = f.input :phone

  .form_actions
    = f.button :submit, "Next", class: 'button'

app/views/artists/favorite.html.haml
%h1 Artist#favorite
%p Find me in app/views/artist/favorite.html.haml

app/views/artists/index.html.haml
.row
	.artistsindex.large-12.columns
		%h1 Browse Tattoo Artists
		- @artists.each do |artist|
			.artistcontainer.large-2.columns.panel.end
				- if artist.avatar_url.present?
					= image_tag ("hashlogo.png")
				- else
					= image_tag ("avatardefault.gif")
				%br
				.artisttext
					= link_to "#{artist.full_name}", artist_path(artist.id)
					%br
					- if artist.location.present?
						= "#{artist.location}"
					- else
						= "Paris, Texas"

app/views/artists/new.html.haml
= render 'artist_steps/artist_wizard_header'

.row
  .large-4.columns
    %h3 Let's start with the basics...

  .large-7.columns
    = simple_form_for(@artist) do |f|
      = f.error_notification

      .field
        = f.input :first_name

      .field
        = f.input :last_name

      .field
        = f.input :location

      .field
        = f.input :tattoo_shop

      .field
        = f.input :tattoo_shop_url, :label => "Tattoo shop website"

      .form_actions
        = f.button :submit, "Next", class: 'button'

app/views/artists/show.html.haml
.artist_page.large-12.columns
  .username
    %h1= "#{@artist.full_name}"
  .artistpic
    = image_tag("hashlogo.png")
%ul.breadcrumbs
  %li
    .social
      = if_social(@artist,:facebook) do
        = build_link(@artist,:facebook)
      / = if_social(@artist, :flickr) do
      /   = build_link(@artist,:flickr)
      = if_social(@artist, :twitter) do
        = build_link(@artist,:twitter)
      = if_social(@artist, :instagram) do
        = build_link(@artist,:instagram)
      = if_social(@artist, :email) do
        = link_to image_tag("email-4-48.png"), "mailto:#{@artist.email}"
  %br
  %li
  %li.current
    %a{:href => "#"} #{@artist.location}
  %li
    %a{:href => "#{@artist.tattoo_shop_url}"} #{@artist.tattoo_shop} 

.row
  .artist_bio.large-4.columns
    - if @artist.bio.present?
      %h3= "Artist Bio"
      %p= "#{@artist.bio}"
      %hr
    - if @artist.specialties.present?
      %h3= "Specialties"
      %p= "#{@artist.specialties}"
  .arttatshow.large-offset-1.large-7.columns
    %h2= "Tattoos"
    - if @artist.tattoos.length == 0
      - if @artist.user_id == current_user.id
        = link_to "Add Your First Tattoo", new_artist_tattoo_path(@artist.id), class: 'button'
      - else
        This artist hasn't added any tattoos to their portfolio yet.
    - else
      - @artist.tattoos.each do |tattoo|
        .tatcontain.large-3.columns
          / = link_to image_tag(tattoo.picture_url(:large_medium_square)), tattoo
          = show_tattoo_photo_profile(tattoo)
      - if user_signed_in?
        - if @artist.user_id == current_user.id
          %hr
          = link_to "Add Another Photo To Your Portfolio", new_artist_tattoo_path(@artist.id), class: 'button'
          = link_to "Edit your portfolio", edit_artist_step_path
    %hr
    .commentsreview
      .row
        = render "reviews"

app/views/artists/unfavorite.html.haml
%h1 Artist#unfavorite
%p Find me in app/views/artist/unfavorite.html.haml

app/views/artists/update.html.haml
%h1 Artist#update
%p Find me in app/views/artist/update.html.haml