config/routes.rb
Myapp::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  post '/change_to_artist' => 'users#change_to_artist'

  get 'tattoos/most_liked' => 'tattoos#most_liked'


  authenticated :user do
    root :to => 'tattoos#index'
  end
  root :to => "home#index"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  ActiveAdmin.routes(self)
  resources :users
  match 'preview' => 'tattoos#preview'
  get 'search' => 'search#search'
  match 'about' => 'home#about'
  match 'quickpreview' => 'home#quickpreview'
  resources :tattoos do
    resources :comments
    member do 
      post :vote_up
      post :vote_down
    end
  end

 
 resources :artists do
    resources :tattoos
    resources :comments
  end
  resources :artist_steps
   post '/artists/:artist_id/comments' => 'comments#create', as: 'create_comment'

end

app/models/tattoo.rb
class Tattoo < ActiveRecord::Base
  acts_as_voteable
  attr_accessible :user_id, :picture, :description, :gender, :body_location, 
                  :studio, :artist_name, :hashtags, :location, :twitter_photo, 
                  :artist_id

  attr_accessible :id, :picture, :description, :gender, :body_location, :studio, 
                  :artist_name, :hashtags, :user_id, :created_at, :updated_at, 
                  :location, :artist_id, :twitter_photo, :as => [:default, :admin]

  mount_uploader :picture, PictureUploader
  validates_presence_of :picture
  
  has_one :tweet
  has_many :comments
  belongs_to :user
  belongs_to :artist
 
  searchable do 
    text :description, :gender, :body_location, :studio, :artist_name, :hashtags, :location, :artist, :user
    text :username 
    text :full_name
  end
  delegate :username, to: :user, allow_nil: true
  delegate :full_name, to: :artist, allow_nil: true
end

app/controllers/tattoos_controller.rb
class TattoosController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :preview, :most_liked]
  layout "full-width", :only => [:index, :search, :preview, :most_liked]
  # GET /tattoos
  # GET /tattoos.json
  def index
    @tattoos = Tattoo.order('created_at DESC')
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tattoos }
    end
  end

  def most_liked
    @tattoos = Tattoo.tally.limit(10).having('COUNT(votes.id) > 0')
    render :index
  end

  # GET /tattoos/1
  # GET /tattoos/1.json
  def show
    @tattoo = Tattoo.find(params[:id])
    @comment = @tattoo.comments.build
    @comments = @tattoo.comments
    @user = @tattoo.user_id
    
    @current_url = request.original_url
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tattoo }
    end
  end

  # GET /tattoos/new
  # GET /tattoos/new.json
  def new
    @tattoo = Tattoo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tattoo }
    end
  end

  # GET /tattoos/1/edit
  def edit
    @tattoo = Tattoo.find(params[:id])
    @users = User.all
  end

  # POST /tattoos
  # POST /tattoos.json
  def create
    tattoo_maker = if params[:tattoo][:artist_id]
      Artist.find(params[:tattoo][:artist_id])
    else
      current_user
    end
    @tattoo = tattoo_maker.tattoos.build(params[:tattoo])
    

    respond_to do |format|
      if @tattoo.save
        if params[:tattoo][:artist_id]
          format.html {redirect_to artist_path(params[:tattoo][:artist_id])}
          format.json { render json: @tattoo, status: :created, location: @tattoo }
        else
          format.html { redirect_to @tattoo, notice: 'Tattoo was successfully created.' }
          format.json { render json: @tattoo, status: :created, location: @tattoo }
        end
      else
        format.html { render action: "new" }
        format.json { render json: @tattoo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tattoos/1
  # PUT /tattoos/1.json
  def update
    @tattoo = Tattoo.find(params[:id])

    respond_to do |format|
      if @tattoo.update_attributes(params[:tattoo])
        format.html { redirect_to @tattoo, notice: 'Your tattoo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tattoo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tattoos/1
  # DELETE /tattoos/1.json
  def destroy
    @tattoo = Tattoo.find(params[:id])
    @tattoo.destroy

    respond_to do |format|
      format.html { redirect_to tattoos_url }
      format.json { head :no_content }
    end
  end

  def vote_up
    @tattoo = Tattoo.find(params[:id])
    current_user.vote_for(@tattoo)
    
    respond_to do |format|
      format.js {render 'vote'}
      format.html{redirect_to :back}
    end
  end

  def vote_down
    @tattoo = Tattoo.find(params[:id])
    current_user.unvote_for(@tattoo)
    respond_to do |format|
      format.js {render 'vote'}
      format.html{redirect_to :back}
    end
  end

    def preview
      @tweets = Tweet.order('created_at DESC')
      @photos = []
      @tweets.each do |tweet|
        tweet.attached_photos.each do |photo|
          @photos << photo.media_url
        end
      end
    
    end

  #   begin
  #     current_user.vote_for(@tattoo = Tattoo.find(params[:id]))
  #     render :nothing => true, :status => 200
  #   rescue ActiveRecord::RecordInvalid
  #     render :nothing => true, :status => 404
  #   end
  # end

end

app/helpers/tattoos_helper.rb
module TattoosHelper
 
end

app/views/tattoos/_artist_tattoo_form.html.erb
<h1>Add a Tattoo To Your Portfolio</h1>
<%= simple_form_for([@artist, @tattoo]) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <%= f.input :picture, :as => :file %>
  </div>
  <div class="field">
    <%= f.input :description, label: "Story", :placeholder => "Share the story of this tattoo. If you don't know full the story describe what's compelling about this tattoo." %>
  </div>
   <div class="field">
    <%= f.input :gender, :collection =>[['Female',:female],['Male',:male]], :as => :radio_buttons %>
  </div>
   <div class="field">
     <%= f.input :body_location, 
    :collection => [['arm',:arm], ['hand',:hand],['neck',:neck],['chest',:chest],['back',:back],['torso',:torso], ['leg',:leg], ['foot',:foot], ['other', :other]]
     %>
    <%#= f.input :body_location, 
    :collection => [['shoulder',:shoulder], ['arm',:arm], ['hand',:hand],['neck',:neck],['chest',:chest],['upper back',:upper_back], ['lower back',:lower_back], ['torso',:torso], ['calf',:calf], ['leg',:leg], ['feet',:feet], ['face',:face], ['other', :other]]
     %>
  </div>
  <div class="field">
    <%= f.input :studio %>
    <%= f.hidden_field :artist_id, :value => params[:artist_id] %>
  </div>
   <div class="field">
    <%= f.input :location, :placeholder => 'eg. Austin, Texas' %>
  </div>
  <div class="field"> 
    <%= f.input :hashtags, :placeholder => "#blackandwhite, #color, #typography, #abstract" %>
  </div>
  <!--   Not showing hashtags until browsing working -->
 <!-- <div class="field"> -->
    <%#= f.input :hashtags %>
  <!-- </div> -->
  <div class="form_action">
    <%= f.button :submit, "Add To My Portfolio" %>
  </div>
<% end %>


<!-- HAML version
%h1 Add a Tattoo To Your Portfolio

= simple_form_for([@artist, @tattoo]) do |f|
  = f.error_notification

  .field
    = f.input :picture, :as => :file
  .field
    = f.input :description
  .field
    = f.input :body_location,
    :collection => [['shoulder',:shoulder], ['arm',:arm], ['upper back',:upper_back], ['torso',:torso], ['lower back',:lower_back], ['face',:face], ['neck',:neck], ['calf',:calf], ['leg',:leg], ['other', :other]]
  .field
    = f.input :studio
    = f.hidden_field :artist_id, :value => params[:artist_id]
  .form_action
    = f.button :submit, "Add To My Portfolio"
 -->

app/views/tattoos/_artists_tattoo_form.html.erb
<h1>Add a Tattoo To Your Portfolio</h1>
<%= simple_form_for([@artist, @tattoo]) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <%= f.input :picture, :as => :file %>
  </div>
  <div class="field">
    <%= f.input :description, label: "Story", :placeholder => "Share the story of this tattoo. If you don't know full the story describe what's compelling about this tattoo." %>
  </div>
   <div class="field">
    <%= f.input :gender, :collection =>[['Female',:female],['Male',:male]], :as => :radio_buttons %>
  </div>
   <div class="field">
     <%= f.input :body_location, 
    :collection => [['arm',:arm], ['hand',:hand],['neck',:neck],['chest',:chest],['back',:back],['torso',:torso], ['leg',:leg], ['foot',:foot], ['other', :other]]
     %>
    <%#= f.input :body_location, 
    :collection => [['shoulder',:shoulder], ['arm',:arm], ['hand',:hand],['neck',:neck],['chest',:chest],['upper back',:upper_back], ['lower back',:lower_back], ['torso',:torso], ['calf',:calf], ['leg',:leg], ['feet',:feet], ['face',:face], ['other', :other]]
     %>
  </div>
  <div class="field">
    <%= f.input :studio %>
    <%= f.hidden_field :artist_id, :value => params[:artist_id] %>
  </div>
   <div class="field">
    <%= f.input :location, :placeholder => 'eg. Austin, Texas' %>
  </div>
  <div class="field"> 
    <%= f.input :hashtags, :placeholder => "#blackandwhite, #color, #typography, #abstract" %>
  </div>
  <!--   Not showing hashtags until browsing working -->
 <!-- <div class="field"> -->
    <%#= f.input :hashtags %>
  <!-- </div> -->
  <div class="form_action">
    <%= f.button :submit, "Add To My Portfolio" %>
  </div>
<% end %>


<!-- HAML version
%h1 Add a Tattoo To Your Portfolio

= simple_form_for([@artist, @tattoo]) do |f|
  = f.error_notification

  .field
    = f.input :picture, :as => :file
  .field
    = f.input :description
  .field
    = f.input :body_location,
    :collection => [['shoulder',:shoulder], ['arm',:arm], ['upper back',:upper_back], ['torso',:torso], ['lower back',:lower_back], ['face',:face], ['neck',:neck], ['calf',:calf], ['leg',:leg], ['other', :other]]
  .field
    = f.input :studio
    = f.hidden_field :artist_id, :value => params[:artist_id]
  .form_action
    = f.button :submit, "Add To My Portfolio"
 -->

app/views/tattoos/_comments.html.erb
<h3>Comments</h3>
<% @comments.each do |comment| %>
  <% if comment.id %>
    <div class="comment_div">
      <div class="user">
        <%= link_to comment.user.username, comment.user %>
      </div>
      <div class="comment_content">
        <%= comment.comment_content %>
      </div>
    </div>
    <% if comment.user == current_user %>
      <div class="comment_delete">
        <%= link_to 'Delete Comment', tattoo_comment_path(@tattoo, comment), method: :delete, data: { confirm: 'Are you sure?' }  %>
      </div>
    <% end %>
  <% end %>
<% end %>
<hr/>
<%= form_for [@tattoo, @comment] do |f| %>
  <% if @comment.errors.any?  %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@comment.errors.count, "error") +'prohibited this comment from being saved:' %>
      </h2>
    </div>
  <% end %>
  <ul>
    <% @tattoo.errors.full_messages.each do |msg|  %>
      <li>
        <%= msg %>
      </li>
    <% end %>
  </ul>
  <div class="field">
    <%= f.text_area :comment_content, :placeholder => "What do you think?" %>
  </div>
  <%= f.submit 'Comment', class: 'button tiny' %>
<% end %>

<!-- HAML version
%h3 Comments
- @comments.each do |comment|
  - if comment.id
    .comment_div
      %div.user= link_to comment.user.username, comment.user
      %div.comment_content= comment.comment_content
    - if comment.user == current_user
      %div.comment_delete= link_to 'Delete Comment', tattoo_comment_path(@tattoo, comment), method: :delete, data: { confirm: 'Are you sure?' } 
      


%hr
= form_for [@tattoo, @comment] do |f|

  - if @comment.errors.any? 
    #error_explanation
      %h2= pluralize(@comment.errors.count, "error") +'prohibited this comment from being saved:'

  %ul
    - @tattoo.errors.full_messages.each do |msg| 
      %li= msg

  .field
    = f.text_area :comment_content, :placeholder => "What do you think?"
  
  = f.submit 'Comment', class: 'button tiny'

 -->

app/views/tattoos/_form.html.erb
<%= simple_form_for(@tattoo) do |f| %>
  <%= f.error_notification %>

  <div class="field">
    <%= f.input :picture, :as => :file %>
  </div>
  <div class="field">
    <%= f.input :description, :placeholder => "Share why you got this particular tattoo. You have a story." %>
  </div>
  <div class="field">
    <%= f.input :gender, :collection =>[['Female',:female],['Male',:male]], :as => :radio_buttons %>
  </div>
  <div class="field">
    <%= f.input :body_location, 
    :collection => [['shoulder',:shoulder], ['arm',:arm], ['upper back',:upper_back], ['torso',:torso], ['lower back',:lower_back], ['face',:face], ['neck',:neck], ['calf',:calf], ['leg',:leg], ['other', :other]]
     %>
  </div>
  <div class="field">
    <%= f.input :artist_name%>
  </div>
  <div class="field">
    <%= f.input :studio%>
  </div>
  <div class="field">
    <%= f.input :location, :placeholder => 'eg. Austin, Texas' %>
  </div>
 <div class="field">
    <%= f.input :hashtags %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, "Submit", class: 'button tiny' %>
  </div>
<% end %>

app/views/tattoos/_liked.html.erb
<div class="color">
  <%= link_to vote_down_tattoo_path(tattoo), method: :post, remote: true do %>
    <%= image_tag('likemom.png',size:'40x40') %>
    <span id="count">
      <%= tattoo.votes_for %>
    </span>
  <% end %>
</div>

<!-- HAML version
.color
  = link_to vote_down_tattoo_path(tattoo), method: :post, remote: true do
    = image_tag('likemom.png',size:'40x40')
    %span#count= tattoo.votes_for
 -->

app/views/tattoos/_not_liked.html.erb
<div class="blackandwhite">
  <%= link_to vote_up_tattoo_path(tattoo), method: :post, remote: true do %>
    <%= image_tag('likemom.png', size:'40x40') %>
    <span id="count">
      <%= tattoo.votes_for %>
    </span>
  <% end %>
</div>

<!-- HAML version
.blackandwhite
  = link_to vote_up_tattoo_path(tattoo), method: :post, remote: true do
    = image_tag('likemom.png', size:'40x40')
    %span#count= tattoo.votes_for -->

app/views/tattoos/_tattoo.html.erb
<div class="masonry-brick">
  <%= show_tattoo_photo(tattoo) %> 
  <%= like_button(tattoo, current_user) %>
</div>

app/views/tattoos/_user_tattoo_form.html.erb
<%= simple_form_for(@tattoo) do |f| %>
  <%= f.error_notification %>

  <div class="field">
    <%= f.input :picture,:as => :file %>
    We want to show you in the best possible light. Upload high quality images that focus on the tattoo. No provocative, profane, or raw images please. 
  </div>
  <div class="field">
    <%= f.input :description, label: "Story", :placeholder => "Share the story of this tattoo. If you don't know full the story describe what's compelling about this tattoo." %>
  </div>
  <div class="field">
    <%= f.input :gender, :collection =>[['Female',:female],['Male',:male]], :as => :radio_buttons %>
  </div>
  <div class="field">
    <%= f.input :body_location, 
    :collection => [['arm',:arm], ['hand',:hand],['neck',:neck],['chest',:chest],['back',:back],['torso',:torso], ['leg',:leg], ['foot',:foot], ['other', :other]]
     %>
  </div>
  <div class="field">
    <%= f.input :artist_name, label:"Artist's Name"%>
  </div>
  <div class="field">
    <%= f.input :studio%>
  </div>
  <div class="field">
    <%= f.input :location, :placeholder => 'eg. Austin, Texas' %>
  </div>
  <div class="field"> 
    <%= f.input :hashtags, :placeholder => "#blackandwhite, #color, #typography, #abstract" %>
  </div> 
  <div class="form-actions">
    <%= f.button :submit, "Submit", class: 'small button' %>
  </div>
<% end %>

app/views/tattoos/edit.html.erb
<!-- Need to fix scroll up feature so header does not show behind transparent nav bar.
New and edit form info pulled inconsistent -->

<h1>Edit a Tat</h1>

<%= render 'user_tattoo_form' %>

<%= link_to 'Delete', @tattoo, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Home', root_path %>


    

app/views/tattoos/index.html.erb
<div id="banner_img">
</div>

<!-- Masonry Container -->
<div id="masonryContainer">
    <% if @tattoos %> 
      <% @tattoos.each do |tattoo| %>
        <div class="masonry-brick">
          <%= show_tattoo_photo(tattoo) %> 
          <%= like_button(tattoo, current_user) %>
        </div>
      <% end %>
     <% end %> 
  <!-- <div class="masonry-brick">
    <img src="http://placehold.it/500x600&text=Item">
  </div>
  <div class="masonry-brick">
    <img src="http://placehold.it/500x700&text=Item">
  </div>
  <div class="masonry-brick">
    <img src="http://placehold.it/500x400&text=Item">
  </div>
  <div class="masonry-brick">
    <img src="http://placehold.it/500x200&text=Item">
  </div>
  <div class="masonry-brick">
    <img src="http://placehold.it/500x300&text=Item">
  </div>
  <div class="masonry-brick">
    <img src="http://placehold.it/500x600&text=Item">
  </div>
  <div class="masonry-brick">
    <img src="http://placehold.it/500x700&text=Item">
  </div>
  <div class="masonry-brick">
    <img src="http://placehold.it/500x400&text=Item">
  </div>
  <div class="masonry-brick">
    <img src="http://placehold.it/500x200&text=Item">
  </div>
  <div class="masonry-brick">
    <img src="http://placehold.it/500x200&text=Item">
  </div>
  <div class="masonry-brick">
    <img src="http://placehold.it/500x300&text=Item">
  </div>
  <div class="masonry-brick">
    <img src="http://placehold.it/500x600&text=Item">
  </div>
  <div class="masonry-brick">
    <img src="http://placehold.it/500x700&text=Item">
  </div>
  <div class="masonry-brick">
    <img src="http://placehold.it/500x400&text=Item">
  </div>
  <div class="masonry-brick">
    <img src="http://placehold.it/500x200&text=Item">
  </div> -->
</div>

<!--<% if cookies["seen_modal-#{current_user.id}"].nil? %>
    <% cookies.permanent["seen_modal-#{current_user.id}"] = true %>
    <div id="myModal" class="reveal-modal">
      <%= image_tag 'sailor_jerry.jpg', :class => "modal_back" %>
      <div class = "modal_text">
        <h2 class><span>Are You A Tattoo Artist?</span></h2>
        <p class="lead">
          <span>Create Your Online Portfolio Now.</span>
        </p>
      </div>

      <div class = 'modal_buttons'>
        <%=link_to "Yes, I'm an artist", new_artist_path, :class =>'button'%>
        <div class ='button closeModal'>No</div>
      </div>


      <a class="close-reveal-modal">&#215;</a>
    </div>
<% end %> -->

app/views/tattoos/new.html.erb
<% if params[:artist_id] %>
  <%= render 'artist_tattoo_form' %>
<% else %>
  <%= render 'user_tattoo_form' %>
<% end %>
<%= link_to 'Back', root_path %>

<!-- HAML version

- if params[:artist_id]
  = render 'artist_tattoo_form'
- else
  = render 'user_tattoo_form'

= link_to 'Back', root_path -->

app/views/tattoos/preview.html.erb
<div id="banner_img">
</div>

<!-- Masonry Container -->
<div id="masonryContainer">
    <% if @photos %> 
      <% @photos.each do |photo| %>
        <div class="masonry-brick">
          <%= link_to image_tag(photo), quickpreview_path%>
        </div>
      <% end %>
    <% end %>
</div>

app/views/tattoos/show.html.erb
<div id="tattoo_info">
  <div class="large-5 columns" id="photo_div">
    <div id="photo">
      <%= show_tattoo_photo(@tattoo) %>
    </div>
    <%= like_button(@tattoo, current_user) %>
    <% if @user == current_user.id %>
      <%= link_to 'Edit', edit_tattoo_path(@tattoo)  %>
     |
      <%= link_to 'Delete', @tattoo, method: :delete, data: { confirm: 'Are you sure?' }  %>
    <% end %>
    <br/>
    <br/>
  </div>
  <div class="large-6 columns end" id="description">
    <% if @tattoo.artist %>
      <p class="title">Added By</p>
      <p class="tattoo_adder">
        <%= link_to "#{@tattoo.artist.full_name}", artist_path(@tattoo.artist) %>
      </p>
    <% else %>
      <p class="title">Added By</p>
      <p class="tattoo_adder">
        <%= link_to "#{@tattoo.user.username}", user_path(@tattoo.user) %>
      </p>
    <% end %>
    <% if @tattoo.description.present? %>
      <p class="title">Story</p>
      <p class="tattoo_description">
        <%= @tattoo.description %>
      </p>
    <% end %>
    <% if @tattoo.gender.present? %>
      <p class="title">Gender</p>
      <p class="tattoo_gender">
        <%= @tattoo.gender %>
      </p>
    <% end %>
    <% if @tattoo.body_location.present? %>
      <p class="title">Location on Body</p>
      <p class="tattoo_body_location">
        <%= @tattoo.body_location %>
      </p>
    <% end %>
    <% if @tattoo.artist_name.present? %>
      <p class="title">Artist</p>
      <p class="tattoo_artist_name">
        <%= @tattoo.artist_name %>
      </p>
    <% end %>
    <% if @tattoo.studio.present? %>
      <p class="title">studio</p>
      <p class="tattoo_studio">
        <%= @tattoo.studio %>
      </p>
    <% end %>
    <% if @tattoo.location.present? %>
      <p class="title">Location</p>
      <p class="tattoo_location">
        <%= @tattoo.location %>
      </p>
    <% end %>
    <% if @tattoo.hashtags.present? %>
      <p class="title">HashTags</p>
      <p class="tattoo_hashtags">
        <%= @tattoo.hashtags %>
      </p>
    <% end %>
  </div>
</div>
<div class="large-12 columns" id="comments"></div>
<%= render 'comments' %>

<!-- HAML version
/ %nav.breadcrumbs
/   = link_to 'Tattoos', tattoos_path
/   = link_to current_user.username, user_path
/   %a.current{:href => "#"} tattoo.title
/
/ = link_to 'Back', tattoos_path
#tattoo_info
  #photo_div.large-5.columns
    #photo
      = show_tattoo_photo(@tattoo)
    = like_button(@tattoo, current_user)

    - if @user == current_user.id
      = link_to 'Edit', edit_tattoo_path(@tattoo) 
      = link_to 'Delete', @tattoo, method: :delete, data: { confirm: 'Are you sure?' } |

    %br
    %br

  #description.large-6.columns.end

    - if @tattoo.artist
      %p.title Added By
      %p.tattoo_adder 
        = link_to "#{@tattoo.artist.full_name}", artist_path(@tattoo.artist)
    - else
      %p.title Added By
      %p.tattoo_adder 
        = link_to "#{@tattoo.user.username}", user_path(@tattoo.user)

    - if @tattoo.description.present?
      %p.title Story
      %p.tattoo_description= @tattoo.description

    - if @tattoo.gender.present?
      %p.title Gender
      %p.tattoo_gender= @tattoo.gender

    - if @tattoo.body_location.present?
      %p.title Location on Body
      %p.tattoo_body_location= @tattoo.body_location

    - if @tattoo.artist_name.present?
      %p.title Artist
      %p.tattoo_artist_name= @tattoo.artist_name

    - if @tattoo.studio.present?
      %p.title studio
      %p.tattoo_studio= @tattoo.studio

    - if @tattoo.location.present?
      %p.title Location
      %p.tattoo_location= @tattoo.location

    - if @tattoo.hashtags.present?
      %p.title HashTags
      %p.tattoo_hashtags= @tattoo.hashtags

#comments.large-12.columns
= render 'comments' -->

app/views/tattoos/vote.js.erb
// alert("<%= @tattoo.id %>");

var $likeButton = $("#<%= dom_id(@tattoo) %>");
if ($likeButton.has(".blackandwhite").length > 0) {
  // $('#like_button').find('a').attr('href', '/tattoos/15/vote_up');
  // $('#like_button').find('#count').html(<%= @tattoo.votes_for %>);
  // $('.blackandwhite').toggleClass('blackandwhite', 'color');
  $likeButton.html("<%= escape_javascript( render :partial => "liked", locals: {tattoo: @tattoo}) %>");
} 

else if ($likeButton.has(".color").length > 0){
  $likeButton.html("<%= escape_javascript( render :partial => "not_liked", locals: {tattoo: @tattoo}) %>");
  // $('#like_button').find('a').attr('href', '/tattoos/15/vote_down');
  // $('#like_button').find('#count').html(<%= @tattoo.votes_for %>);
  // $('.color').toggleClass('color', 'blackandwhite');
}