config/routes.rb
Myapp::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  post '/change_to_artist' => 'users#change_to_artist'

  get 'tattoos/most_liked' => 'tattoos#most_liked'


  authenticated :user do
    root :to => 'tattoos#index'
  end
  root :to => "home#index"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  ActiveAdmin.routes(self)
  resources :users
  match 'preview' => 'tattoos#preview'
  get 'search' => 'search#search'
  match 'about' => 'home#about'
  match 'quickpreview' => 'home#quickpreview'
  resources :tattoos do
    resources :comments
    member do 
      post :vote_up
      post :vote_down
    end
  end

 
 resources :artists do
    resources :tattoos
    resources :comments
  end
  resources :artist_steps
   post '/artists/:artist_id/comments' => 'comments#create', as: 'create_comment'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
layout "full-width", :only => [:index]
  def index
    
  end

  def about

  end

  def preview

  end


end

app/helpers/home_helper.rb
module HomeHelper

  def resource_name
    :user
  end

   def resource
     @resource ||= User.new
   end

   def devise_mapping
     @devise_mapping ||= Devise.mappings[:user]
   end

end

app/views/home/about.html.erb
<div class="abouttext large-12 columns">
  <h1>HASHTAT</h1>
  <p class="top">
    is a community for meaningful tattoo art. We not only love the art but the stories that influence the art.</p> 
      <br>
      <p class="top">Browse tattoos | Read why people got their tattoos | Search tattoos by gender, body part, artist, etc. </p>
</div>

<div class="subtext large-6 columns">
  <h1>BUILT BY</h1>
  <p>
      Three young women, Tina, Shannon, and Doa, who learned to code in 10 weeks without a lick of programming experience prior. Hashtat was born out of our pure love for art, story, and community. In supporting hashtat, you are also supporting the movement of women entering jobs in technology.</p>
      <p>We stand on the shoulders of the patient teachers, mentors and developers who believed in us and inspire us to keep building. We are humbled with the understanding that nothing is built alone.
   <!--  <p>
      Many thanks to the MKS founders and our classmates, Micah Frazier, Aaron Scruggs,  Matthew Buck, Mike Ornellas, Nathaniel Jones, Gilbert Garza, Christina Day, Scott Bellware, Mando Escamilla, Damon Clinkscales, Sam Kapila, Nick Zadrozny, and Andres Angulo.
    </p> -->
  </p>
</div>
<div class="subtext large-offset-1 columns large-5 columns">
  <h1>SAY HI</h1>
  <p>
    We built hashtat for you and need your feedback to be better! Let us know if you found a bug, if you have ideas, or just wanna say hiya.
    <p>
      Tweet us at <a href="https://twitter.com/mshashtat">mshashtat</a> or e-mail 
        <a href="mailto:mshashtat@gmail.com">mshashtat@gmail.com</a>.
    </p>
  </p>
</div>
</div>
<div class="row pics">
  <div class="large-4 columns">
    <div class="avatar tina">
      <%= image_tag("ctina.gif") %>
      <p>Tina</p>
      <p class="bio">
        Tattoo wish: Back tattoo commemorating grandfather's philosophy of convergence. That everything comes together in the end. (black ink)
        <br/>
      </p>
    </div>
  </div>
  <div class="large-4 columns">
    <div class="shannon avatar">
      <%= image_tag("cshannon.gif") %>
      <p>Shannon</p>
      <p class="bio">
        Tattoo wish: to be detemined (color ink)
        <br/>
      </p>
    </div>
  </div>
  <div class="large-4 columns">
    <div class="doa avatar">
      <%= image_tag("cdoa.gif") %>
      <p>Doa</p>
      <p class="bio">
        Tattoo wish:  A wrist tattoo of a sparrow with an arrow through its eye. Dad used to tell me not to blind myself with too much and to focus on the beauty that is present. (black ink)
        <br/>
      </p>
    </div>
  </div>
</div>
<div class="subtext large-6 columns">

<!-- HAML version

.abouttext.large-12.columns
  %h1 HASHTAT
  %p.top
    is a community for tattoo art and the stories behind the ink. We're three art-loving women who learned to code in 10 weeks, culminating in hashtat.com. We attended Austin's first development bootcamp,
    = succeed "," do
      %a{:href => "http://www.themakersquare.com"} MakerSquare
    and didn't know a lick of code prior to the experience.


.row.pics
  .large-4.columns
    .avatar.tina
      = image_tag("ctina.gif")
      %p Tina
      %p.bio 
        Full Stack Merge Master
        %br @tinapshah
  .large-4.columns
    .shannon.avatar
      = image_tag("cshannon.gif")
      %p Shannon
      %p.bio 
        The Back End Beast
        %br @s_byrne
  .large-4.columns
    .doa.avatar
      = image_tag("cdoa.gif")
      %p Doa
      %p.bio 
        The Front End Freak
        %br @doaboa

.subtext.large-6.columns
  %h1 PLUS ONE
  %p
    We stand on the shoulders of the patient teachers, mentors and coders who believed in us and inspire us to keep building.
    %p
      Many thanks to the MKS founders and our classmates, Micah Frazier, Aaron Scruggs,  Matthew Buck, Mike Ornellas, Nathaniel Jones, Gilbert Garza, Christina Day, Scott Bellware, Mando Escamilla, Damon Clinkscales, Sam Kapila, Nick Zadrozny, and Andres Angulo.


.subtext.large-offset-1.columns.large-5.columns
  %h1 CONTACT
  %p 
    We built HashTat for you, so when it comes to your feedback, we're all ears. Let us know if you found a bug, if you have ideas to make the site better, or just to say hi.
    %p
      Tweet us @mrhashtat or shoot an e-mail to
      = succeed "," do
        %a{:href => "mailto:mshashtat@gmail.com"} mshashtat@gmail.com -->

app/views/home/index.html.erb
<div id="logModal" class="reveal-modal small" style="padding: 0px;">
  <div class="section-container auto" data-section>
    <section class="active">
      <p class="title" data-section-title><a href="#panel1">Sign Up</a></p>
      <div class="content" data-section-content>
        <br>
        <hr>
        <%= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => {:class => 'form-vertical' }) do |f| %>
            <%= f.error_notification %>
            <%= display_base_errors resource %>
            <%= f.input :username, :label => "Username", :autofocus => true %>
            <%= f.input :email, :required => true %>
            <% if f.object.password_required? %>
                <%= f.input :password, :required => true %>
                <%= f.input :password_confirmation, :required => true %>
            <% end %>
            <%= f.label "I have read and accept the terms of service" %>
            <%= f.check_box :terms_of_service %>
            <%= f.label "I would like to be signed up for the newsletter" %>
            <%= f.check_box :newsletter %>
            <br>

            <%= f.button :submit, 'Sign Up', :class => 'small button' %>
        <% end %>
        <% if devise_mapping.omniauthable? %>
            <% User.omniauth_providers.each do |provider| %>
                <%= link_to "Sign Up with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider), :class => 'medium button' %>
                <br/>
            <% end %>
          <% end %>
          <br>
            <hr>
              <%= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => {:class => 'form-vertical' }) do |f| %>
                <%= f.error_notification %>
                <%= display_base_errors resource %>
                <%= f.input :username, :label => "Username", :autofocus => true %>
                <%= f.input :email, :required => true %>
                <% if f.object.password_required? %>
                  <%= f.input :password, :required => true %>
                  <%= f.input :password_confirmation, :required => true %>
                <% end %>
                <%= f.label "I have read and accept the terms of service" %>
                <%= f.check_box :terms_of_service %>
                <%= f.label "I would like to be signed up for the newsletter" %>
                <%= f.check_box :newsletter %>
                <br>

                <%= f.button :submit, 'Sign Up', :class => 'small button' %>
              <% end %>
            </hr>
          </br>
        </div>
        <% end %>
      </div>
    </section>
    <section>
      <p class="title" data-section-title><a href="#panel2">Login</a></p>
      <div class="content" data-section-content>
        <div class="log_in">
          <h2>Log in.</h2>
          <% if devise_mapping.omniauthable? %>
              <% User.omniauth_providers.each do |provider| %>
                  <%= link_to "Log In with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider), :class => 'medium button twitter_btn' %>
                  <br/>
              <% end %>
          <% end %>
          <br>
          <hr>
          <%= simple_form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => {:class => 'form-vertical' }) do |f| %>
              <%= f.input :email, :autofocus => true %>
              <% if devise_mapping.recoverable? && controller_name != 'passwords' %>
                  <%= f.input :password %>
                  <% if devise_mapping.recoverable? && controller_name != 'passwords' %>
                      <%= link_to "Forgot your password?", new_password_path(resource_name) %>
                      <br/>
                  <% end %>
                  <br/>
              <% end %>
              <%= f.input :remember_me, :as => :boolean if devise_mapping.rememberable? %>
              <br>
              <%= f.button :submit, "Log in", :class => 'small button' %>
          <% end %>
        </div>
      </div>
    </section>
  </div>
  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/home/preview.html.erb
<h1> Welcome to H A S H T A T </h1>

<h5>We are community for tattoo art and the stories behind them.<h5>

<h5>To see more photos or find out more details sign up in 3 seconds.<h5>
  
<div class = "sign_up">
    <br>
      <%- if devise_mapping.omniauthable? %>
        <%- User.omniauth_providers.each do |provider| %>
        <%= link_to "Sign Up with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider), :class => 'medium button twitter_btn' %><br />
        <% end -%>
      <% end -%>
      <br>
      <hr>
      <%= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => {:class => 'form-vertical' }) do |f| %>
        <%= f.error_notification %>
        <%= display_base_errors resource %>
        <%= f.input :username, :label => "Username", :autofocus => true %>
        <%= f.input :email, :required => true %>
        <% if f.object.password_required? %>
          <%= f.input :password, :required => true %>
          <%= f.input :password_confirmation, :required => true %>
        <% end %>
        <%= f.button :submit, 'Sign Up', :class => 'small button' %>
      <% end %>
    </div>

app/views/home/quickpreview.html.erb
<div class="row">
  <div class="qptext">
    <h1>Welcome to H A S H T A T</h1>
    <h5>
      We are community for tattoo art and the stories behind them.
      <h5>
        To see more photos or find out more details sign up in 3 seconds.
      </h5>
    </h5>
  </div>
  <div class="qpsign_up">
    <br>
      <% if devise_mapping.omniauthable? %>
        <% User.omniauth_providers.each do |provider| %>
          <%= link_to "Sign Up with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider), :class => 'medium button twitter_btn' %>
          <br/>
        <% end %>
      <% end %>
      <br>
        <hr>
          <%= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => {:class => 'form-vertical' }) do |f| %>
            <%= f.error_notification %>
            <%= display_base_errors resource %>
            <%= f.input :username, :label => "Username", :autofocus => true %>
            <%= f.input :email, :required => true %>
            <% if f.object.password_required? %>
              <%= f.input :password, :required => true %>
              <%= f.input :password_confirmation, :required => true %>
            <% end %>
            <%= f.button :submit, 'Sign Up', :class => 'small button' %>
          <% end %>
        </hr>
      </br>
    </br>
  </div>
</div>

<!-- HAML version
.row
  .qptext
    %h1 Welcome to H A S H T A T
    %h5
      We are community for tattoo art and the stories behind them.
      %h5
        To see more photos or find out more details sign up in 3 seconds.
  .qpsign_up
    %br
      - if devise_mapping.omniauthable?
        - User.omniauth_providers.each do |provider|
          = link_to "Sign Up with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider), :class => 'medium button twitter_btn'
          %br/
      %br
        %hr
          = simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => {:class => 'form-vertical' }) do |f|
            = f.error_notification
            = display_base_errors resource
            = f.input :username, :label => "Username", :autofocus => true
            = f.input :email, :required => true
            - if f.object.password_required?
              = f.input :password, :required => true
              = f.input :password_confirmation, :required => true
            = f.button :submit, 'Sign Up', :class => 'small button' -->