config/routes.rb
Myapp::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  post '/change_to_artist' => 'users#change_to_artist'

  get 'tattoos/most_liked' => 'tattoos#most_liked'


  authenticated :user do
    root :to => 'tattoos#index'
  end
  root :to => "home#index"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  ActiveAdmin.routes(self)
  resources :users
  match 'preview' => 'tattoos#preview'
  get 'search' => 'search#search'
  match 'about' => 'home#about'
  match 'quickpreview' => 'home#quickpreview'
  resources :tattoos do
    resources :comments
    member do 
      post :vote_up
      post :vote_down
    end
  end

 
 resources :artists do
    resources :tattoos
    resources :comments
  end
  resources :artist_steps
   post '/artists/:artist_id/comments' => 'comments#create', as: 'create_comment'

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) && !msg.empty? %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_modal.html.erb
<div id="login_signup_modal" style="width: 900px; left: 830px; display: block;"><div class="ui-dialog">
  <a class="ui-dialog-titlebar-close ui-corner-all close"></a>
  <div class="ui-dialog-content">
    <div class="signup_form" style="display: none;">
      <div class="logo"></div>
      <div class="message">
        <div class="copy">The world’s greatest art, online. Sign up<br>to discover and collect your favorites.</div>
      </div>
      <div class="signup_buttons">
        <a class="signup_with_facebook" href="/users/auth/facebook?sign_up=true">Sign Up with Facebook</a>
        <a class="signup_with_twitter" href="/users/auth/twitter?sign_up=true">Sign Up with Twitter</a>
        <a class="signup_with_email" href="/users/invitation/accept?email=1">Sign Up Using Your Email Address</a>
      </div>
      <div class="terms_copy">
        By creating your Artsy account you agree to our
        <br>
        <a class="terms_link faux-underline" href="/terms" target="_blank">Terms of Use</a>
        and
        <a class="privacy_link faux-underline" href="/privacy" target="_blank">Privacy Policy</a>.
      </div>
      <div class="login_copy bottom-text">
        Already have an account?
        <a class="log_in log_in_button faux-underline">Log in</a>
      </div>
    </div>

    <div class="login_form" style="display: block;">
      <div class="logo"></div>
      <div class="errors error_message"></div>
      <div class="login_providers">
        <div class="social_providers">
          <div class="message">
            Log In With Facebook or Twitter
          </div>
          <a class="enter_with_facebook" href="/users/auth/facebook">Facebook</a>
          <a class="enter_with_twitter" href="/users/auth/twitter">Twitter</a>
        </div>
        <form accept-charset="UTF-8" action="https://artsy.net/users/sign_in" class="formatted" method="post">
          <div class="artsy_placeholder_wrapper" style="position: relative;"><div class="artsy_placeholder" style="position: absolute; top: 0px; left: 0px; color: rgb(153, 153, 153);">Email</div><input autocomplete="on" autofocus="autofocus" name="user[email]" type="email"></div>
          <div class="log_in">
            <div class="artsy_placeholder_wrapper" style="position: relative;"><div class="artsy_placeholder" style="position: absolute; top: 0px; left: 0px; color: rgb(153, 153, 153);">Password</div><input autocomplete="on" name="user[password]" type="password"></div>
            <button class="log_in text block dark">
              <div class="spinner_container">
                <div class="spinner w_p"></div>
              </div>
              Log in
            </button>
            <div class="checkbox_container">
              <input checked="checked" class="checkbox" name="user[remember_me]" type="checkbox" value="1">
              <label class="checkbox" for="user[remember_me]">Remember me</label>
            </div>
            <a class="forgot_password faux-underline" href="#">Forgot password?</a>
          </div>
          <div class="forgot">
            <button class="forgot_password text block dark">
              <div class="spinner_container">
                <div class="spinner w_p"></div>
              </div>
              Send me reset instructions
            </button>
            <a class="forgot_password faux-underline" href="#">I remember it!</a>
          </div>
        </form>
      </div>
      <div class="confirmation_sent">
        <h3>Please check your email for instructions on how to reset your password.</h3>
        <a class="back_to_login faux-underline">Log in</a>
      </div>
      <div class="back_to_signup bottom-text">
        Don't have an account?
        <a class="sign_up_button faux-underline">Sign up</a>
      </div>
    </div>

  </div>
</div>
</div>

app/views/layouts/_navigation.html.erb
<!-- Header and Nav -->
 <div class = "fixed">
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1>
          <%= link_to "# H A S H T A T", root_path %>
        </h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>
 
    <section class="top-bar-section">
 
      <!-- Right Nav Section -->
      <ul class="right">
        <% if user_signed_in? %>
          <li>
          <%= link_to "Popular Tattoos", controller: "/tattoos", action: "most_liked" %>
          </li>
          <li>
          <%= link_to "Recent Tattoos", tattoos_path %>
          </li>
          <%# unless current_user.artist %>
            <!-- <li> -->
              <%#= link_to "Create Tattoo Artist Page", new_artist_path %>
            <!-- </li> -->
          <%# end %>
        <% end %>

        <% if user_signed_in? %>
          <% if current_user.artist %>
            <li>
              <%= link_to "Add a Tat", new_artist_tattoo_path(current_user.artist.id) %>
            </li>
          <% else %>
            <li>
              <%= link_to "Add a Tat", new_tattoo_path %>
            </li>
          <% end %>
          <li id="search">
           <%= form_tag '/search', :method => :get do %>
            <%= text_field_tag :q, params[:q], :placeholder => "Search any field" %>
          </li>
           <li>
          <%= link_to "About", about_path %>
          </li>
          <% end %>
          <li class="has-dropdown">
            <%=link_to current_user.username, user_path(current_user) %>

            <ul class="dropdown">

              <% if current_user.artist %>
                <li>
                  <%= link_to 'My Artist Profile', artist_path(current_user.artist.id) %>
                </li>
              <% end %>
      
              <li>
              <%= link_to 'Settings', edit_user_registration_path %>
              </li>
              <li>
              <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
            <li>
          </ul>
        </li>
        <%# else %>
          <li>
            <%#= link_to "Quick Preview", preview_path %>
          </li>
        <% end %>
      </ul>
    </section>
  </nav>
</div>
 
 
  <!-- End Header and Nav -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns:fb="http://ogp.me/ns/fb#">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "HashTat" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "HashTat" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>




  <body class="<%= controller_name %> <%= action_name %>">

   

<!-- Nav -->

      
  <%= render 'layouts/navigation' %>

  <!-- Content -->

  
    <div class="row">
      <div id="main" role="main" class="large-12 columns">
<!--         <%= render 'layouts/messages' %> -->
        <%= yield %>
      </div>
    </div>
    
 <!-- Facebook Like JavaScript -->
<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=1376057452618930";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>

  </body>
</html>

app/views/layouts/full-width.html.erb
<!DOCTYPE html>
<html xmlns:fb="http://ogp.me/ns/fb#">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "HashTat" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "HashTat" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>



  <body class="<%= controller_name %> <%= action_name %>">
 

   

<!-- Nav -->

      
  <%= render 'layouts/navigation' %>

  
  
  <!-- SideNav -->
<!--   <div id="navbar" class="small-1 column">
    <div id="navbar" class="fixed">
      <ul class="side-nav"> -->
       <!-- <<li>
          <%= link_to "+Tat", new_tattoo_path %> 
        </li>  -->
        <!-- <li><a href="#">Link 2</a></li>
        <li><a href="#">Link 3</a></li>
        <li><a href="#">Link 4</a></li> -->
   <!--    </ul>
    </div>
  </div> -->

  <!-- Content -->

    <div class="row full-width">
      <div id="main" role="main" class="large-12 columns" style="margin-top:0;">
<!--         <%= render 'layouts/messages' %>
 -->        <%= yield %>
      </div>
    </div>

  
  <!-- Footer -->
  
<!--   <footer class="row">
    <div class="large-12 columns">
      <hr />
      <div class="row">
        <div class="large-6 columns">
          <p>&copy; HackHAUS</p>
        </div>
        <div class="large-6 columns">
          <ul class="inline-list right">
            <li><a href="#">Facebook</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Pinterest</a></li>
            <li><a href="#">E-mail</a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
 -->

 <!-- Facebook Like JavaScript -->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=1376057452618930";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

  </body>
</html>